### ISSUE TITLE
Question about synthesizing blurrys and comparison

### ISSUE THREAD

**Issue by HaoDot** [pp00704831/Stripformer-ECCV-2022-#1]
Hi @pp00704831 , a nice architecture for single image deblurring. However, there are some questions. Hope you can reply. Thx.

- Q1: How to synthesize blurrys? 
  - How many sharps are used to average in order to output a blurry image?
  - Did you use the interpolated frames to synthesize the blurrys?

- Q2: the number of performance
  - It seems that you didn't finetune any S.O.T.A. model mentioned in your paper. Do you just use the number in their original papers?

Waiting for your reply! Thx.

**Comment by pp00704831** [comment]
Hello @Ginobili-20,  

For Q1, we use the original GoPro training set that contains 2103 images for training.

For Q2, If the paper has released codes or deblurred results like MPRNet, we would calculate the performance according to the codes or deblurred results. Otherwise, we directly use the scores from the table in their papers.

Thank you for your interest!
